Remove irssi

diff --git a/scripts/rtinst b/scripts/rtinst
--- a/scripts/rtinst
+++ b/scripts/rtinst
@@ -24,7 +24,7 @@ xmlrpc_url="https://svn.code.sf.net/p/xmlrpc-c/code/advanced/"
 xmlrpc_url_alt="https://github.com/mirror/xmlrpc-c"
 
 ru_url="https://github.com/Novik/ruTorrent/"
-adl_url="https://github.com/autodl-community/"
+#adl_url="https://github.com/autodl-community/"
 
 if [ $(dpkg-query -W -f='${Status}' lsb-release 2>/dev/null | grep -c "ok installed") -eq 0 ]; then
 echo "Installing lsb-release"
@@ -62,8 +62,10 @@ fi
 export serverip=$(ip route get 8.8.8.8 | awk 'NR==1 {print $7}')
 export logfile="/dev/null"
 webpass=''
-cronline1="@reboot sleep 10; /usr/local/bin/rtcheck irssi rtorrent"
-cronline2="*/10 * * * * /usr/local/bin/rtcheck irssi rtorrent"
+#cronline1="@reboot sleep 10; /usr/local/bin/rtcheck irssi rtorrent"
+#cronline2="*/10 * * * * /usr/local/bin/rtcheck irssi rtorrent"
+cronline1="@reboot sleep 10; /usr/local/bin/rtcheck rtorrent"
+cronline2="*/10 * * * * /usr/local/bin/rtcheck rtorrent"
 dlflag=1
 portdefault=1
 
@@ -72,7 +74,8 @@ sshport=''
 rudevflag=1
 rurelease=master
 passfile='/etc/nginx/.htpasswd'
-package_list="sudo nano autoconf build-essential ca-certificates comerr-dev curl cfv dtach htop irssi libcloog-ppl-dev libcppunit-dev $libcver libncurses5-dev libterm-readline-gnu-perl libsigc++-2.0-dev libperl-dev libtool libxml2-dev ncurses-base ncurses-term ntp patch pkg-config $phpver-fpm $phpver $phpver-cli $phpver-dev $phpver-curl $geoipver $phpver-xmlrpc python-scgi screen subversion texinfo unzip zlib1g-dev libcurl4-openssl-dev mediainfo software-properties-common aptitude $phpver-json nginx-full apache2-utils git libarchive-zip-perl libnet-ssleay-perl libhtml-parser-perl libxml-libxml-perl libjson-perl libjson-xs-perl libxml-libxslt-perl libjson-rpc-perl libarchive-zip-perl"
+#package_list="sudo nano autoconf build-essential ca-certificates comerr-dev curl cfv dtach htop irssi libcloog-ppl-dev libcppunit-dev $libcver libncurses5-dev libterm-readline-gnu-perl libsigc++-2.0-dev libperl-dev libtool libxml2-dev ncurses-base ncurses-term ntp patch pkg-config $phpver-fpm $phpver $phpver-cli $phpver-dev $phpver-curl $geoipver $phpver-xmlrpc python-scgi screen subversion texinfo unzip zlib1g-dev libcurl4-openssl-dev mediainfo software-properties-common aptitude $phpver-json nginx-full apache2-utils git libarchive-zip-perl libnet-ssleay-perl libhtml-parser-perl libxml-libxml-perl libjson-perl libjson-xs-perl libxml-libxslt-perl libjson-rpc-perl libarchive-zip-perl"
+package_list="sudo nano autoconf build-essential ca-certificates comerr-dev curl cfv dtach htop libcloog-ppl-dev libcppunit-dev $libcver libncurses5-dev libterm-readline-gnu-perl libsigc++-2.0-dev libperl-dev libtool libxml2-dev ncurses-base ncurses-term ntp patch pkg-config $phpver-fpm $phpver $phpver-cli $phpver-dev $phpver-curl $geoipver $phpver-xmlrpc python-scgi screen subversion texinfo unzip zlib1g-dev libcurl4-openssl-dev mediainfo software-properties-common aptitude $phpver-json nginx-full apache2-utils git libarchive-zip-perl libnet-ssleay-perl libhtml-parser-perl libxml-libxml-perl libjson-perl libjson-xs-perl libxml-libxslt-perl libjson-rpc-perl libarchive-zip-perl"
 Install_list=""
 unixpass=""
 passflag=0
@@ -298,7 +301,7 @@ if [[ $xmlrpc_repo = 1 ]]; then
 fi
 
 echo -n "RuTorrent: ";check_url $ru_url && echo "OK" || { echo "FAIL"; major_repo=1; }
-echo -n "Autodl-irssi: "; check_url $adl_url && echo "OK" || { echo "FAIL"; major_repo=1; }
+#echo -n "Autodl-irssi: "; check_url $adl_url && echo "OK" || { echo "FAIL"; major_repo=1; }
 
 if [ $os_repo = 1 ]; then
   echo "Some of your $osname mirrors are down, try again later"
@@ -408,7 +411,7 @@ if [ -z "$webpass" ]  && [ $passflag != 2 ]; then
       passflag=2
     fi
   fi
-  
+
   if [ $passflag != 2 ]; then
     echo "Set Password for RuTorrent web client"
     webpass=$(set_pass)
@@ -449,7 +452,7 @@ echo "No more user input required, you can complete unattended"
 echo "It will take approx 10 minutes for the script to complete"
 echo
 
-# kill apt-daily.service if running 
+# kill apt-daily.service if running
 if [[ $(systemctl list-units --all apt-daily.service | fgrep -c apt-daily.service) -gt 0 ]]; then
   systemctl stop apt-daily.service >> $logfile 2>&1
   systemctl kill --kill-who=all apt-daily.service >> $logfile 2>&1
@@ -814,50 +817,50 @@ fi
 ### INSTALL AUTODL-IRSSI ###
 ###############################
 
-echo "Installing autodl-irssi" | tee -a $logfile
-adlport=$(random 36001 36100)
-adlpass=$(genpasswd $(random 12 16))
-
-mkdir -p $home/.irssi/scripts/autorun
-cd $home/.irssi/scripts
-curl -sL http://git.io/vlcND | grep -Po '(?<="browser_download_url": ")(.*-v[\d.]+.zip)' | xargs wget --quiet -O autodl-irssi.zip
-unzip -qq -o autodl-irssi.zip | tee -a $logfile
-rm autodl-irssi.zip
-cp autodl-irssi.pl autorun/
-mkdir -p $home/.autodl
-
-cd /var/www/rutorrent/plugins
-git clone -q https://github.com/autodl-community/autodl-rutorrent.git autodl-irssi | tee -a $home/rtinst.info
-
-mkdir /var/www/rutorrent/conf/users/$user/plugins/autodl-irssi
-
-touch /var/www/rutorrent/conf/users/$user/plugins/autodl-irssi/conf.php
-
-echo "<?php" > /var/www/rutorrent/conf/users/$user/plugins/autodl-irssi/conf.php
-echo >> /var/www/rutorrent/conf/users/$user/plugins/autodl-irssi/conf.php
-echo "\$autodlPort = $adlport;" >> /var/www/rutorrent/conf/users/$user/plugins/autodl-irssi/conf.php
-echo "\$autodlPassword = \"$adlpass\";" >> /var/www/rutorrent/conf/users/$user/plugins/autodl-irssi/conf.php
-echo >> /var/www/rutorrent/conf/users/$user/plugins/autodl-irssi/conf.php
-echo "?>" >> /var/www/rutorrent/conf/users/$user/plugins/autodl-irssi/conf.php
-
-cd $home/.autodl
-rm -f autodl2.cfg
-
-if [ -f "autodl.cfg" ]; then
-  if (grep -sq gui-server-port autodl.cfg) && (grep -sq gui-server-password autodl.cfg); then
-    sed -i "/gui-server-port/ c\gui-server-port = $adlport" autodl.cfg
-    sed -i "/gui-server-password/ c\gui-server-password = $adlpass" autodl.cfg
-  else
-    sed -i '/gui-server-port/ d' autodl.cfg
-    sed -i '/gui-server-password/ d' autodl.cfg
-    echo >> autodl.cfg
-    sed -i "1s/^/[options]\ngui-server-port = $adlport\ngui-server-password = $adlpass\n/" autodl.cfg
-  fi
-else
-  echo "[options]" > autodl.cfg
-  echo "gui-server-port = $adlport" >> autodl.cfg
-  echo "gui-server-password = $adlpass" >> autodl.cfg
-fi
+# echo "Installing autodl-irssi" | tee -a $logfile
+# adlport=$(random 36001 36100)
+# adlpass=$(genpasswd $(random 12 16))
+#
+# mkdir -p $home/.irssi/scripts/autorun
+# cd $home/.irssi/scripts
+# curl -sL http://git.io/vlcND | grep -Po '(?<="browser_download_url": ")(.*-v[\d.]+.zip)' | xargs wget --quiet -O autodl-irssi.zip
+# unzip -qq -o autodl-irssi.zip | tee -a $logfile
+# rm autodl-irssi.zip
+# cp autodl-irssi.pl autorun/
+# mkdir -p $home/.autodl
+#
+# cd /var/www/rutorrent/plugins
+# git clone -q https://github.com/autodl-community/autodl-rutorrent.git autodl-irssi | tee -a $home/rtinst.info
+#
+# mkdir /var/www/rutorrent/conf/users/$user/plugins/autodl-irssi
+#
+# touch /var/www/rutorrent/conf/users/$user/plugins/autodl-irssi/conf.php
+#
+# echo "<?php" > /var/www/rutorrent/conf/users/$user/plugins/autodl-irssi/conf.php
+# echo >> /var/www/rutorrent/conf/users/$user/plugins/autodl-irssi/conf.php
+# echo "\$autodlPort = $adlport;" >> /var/www/rutorrent/conf/users/$user/plugins/autodl-irssi/conf.php
+# echo "\$autodlPassword = \"$adlpass\";" >> /var/www/rutorrent/conf/users/$user/plugins/autodl-irssi/conf.php
+# echo >> /var/www/rutorrent/conf/users/$user/plugins/autodl-irssi/conf.php
+# echo "?>" >> /var/www/rutorrent/conf/users/$user/plugins/autodl-irssi/conf.php
+#
+# cd $home/.autodl
+# rm -f autodl2.cfg
+#
+# if [ -f "autodl.cfg" ]; then
+#   if (grep -sq gui-server-port autodl.cfg) && (grep -sq gui-server-password autodl.cfg); then
+#     sed -i "/gui-server-port/ c\gui-server-port = $adlport" autodl.cfg
+#     sed -i "/gui-server-password/ c\gui-server-password = $adlpass" autodl.cfg
+#   else
+#     sed -i '/gui-server-port/ d' autodl.cfg
+#     sed -i '/gui-server-password/ d' autodl.cfg
+#     echo >> autodl.cfg
+#     sed -i "1s/^/[options]\ngui-server-port = $adlport\ngui-server-password = $adlpass\n/" autodl.cfg
+#   fi
+# else
+#   echo "[options]" > autodl.cfg
+#   echo "gui-server-port = $adlport" >> autodl.cfg
+#   echo "gui-server-password = $adlpass" >> autodl.cfg
+# fi
 
 ###############################
 ### FINAL TASKS ###
@@ -888,7 +891,7 @@ if [ -z "$(crontab -u $user -l | grep "$cronline1")" ]; then
     (crontab -u $user -l; echo "$cronline1" ) | crontab -u $user - >> $logfile 2>&1
 fi
 
-if [ -z  "$(crontab -u $user -l | grep "\*/10 \* \* \* \* /usr/local/bin/rtcheck irssi rtorrent")" ]; then
+if [ -z  "$(crontab -u $user -l | grep "\*/10 \* \* \* \* /usr/local/bin/rtcheck rtorrent")" ]; then
     (crontab -u $user -l; echo "$cronline2" ) | crontab -u $user - >> $logfile 2>&1
 fi
 
